services:
  backend:
    image: ghcr.io/airton659/dashboardcompras-backend:latest
    container_name: dashboardcorrente_backend
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Rm__Host=${RM_HOST}
      - Rm__Port=${RM_PORT}
      - Rm__Name=${RM_NAME}
      - Rm__User=${RM_USER}
      - Rm__Password=${RM_PASSWORD}
      - Rm__DbClient=FreeTDS
      - Rm__ConnectionStringOverride=
    ports:
      - "8089:8080"

  frontend:
    image: ghcr.io/airton659/dashboardcompras-frontend:latest
    container_name: dashboardcorrente_frontend
    restart: unless-stopped
    ports:
      - "8088:80"
    depends_on:
      - backend
