FROM mcr.microsoft.com/dotnet/sdk:10.0
WORKDIR /app

RUN sed -i -E 's#http://(archive|security)\.ubuntu\.com#https://\1.ubuntu.com#g' /etc/apt/sources.list /etc/apt/sources.list.d/*.sources; \
    apt-get update && \
    apt-get install -y --no-install-recommends unixodbc tdsodbc curl && \
    rm -rf /var/lib/apt/lists/*

RUN printf '[FreeTDS]\nDescription=FreeTDS Driver\nDriver=/usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so\n' \
    > /etc/odbcinst.ini

ENTRYPOINT ["dotnet", "watch", "run", "--project", "DashboardCorrente.csproj", "--urls", "http://0.0.0.0:8080"]
